<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net5.0;net6.0;net8.0;net9.0;net10.0</TargetFrameworks>

		<Version>3.3.0.0</Version>
		<AssemblyVersion>3.3.0.0</AssemblyVersion>
		<FileVersion>3.3.0.0</FileVersion>

		<Authors>Canducci</Authors>
		<Company>Canducci</Company>

		<PackageProjectUrl>https://github.com/fulviocanducci/Canducci.Paginated</PackageProjectUrl>
		<RepositoryUrl>https://github.com/fulviocanducci/Canducci.Paginated</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<PackageTags>Paginated Mvc Core</PackageTags>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<Description>Pagination Razor Pages and Traditional MVC</Description>

		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>

		<PackageIcon>ico.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>

		<Copyright>Canducci</Copyright>
		<CheckEolTargetFramework>false</CheckEolTargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Canducci.Pagination\Canducci.Pagination.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\images\ico.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

</Project>